complexshare/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Route::get('/quit', 'QuitController@index')->name('quit');

Route::post('/quit', 'QuitController@delete')->name('quit.delete');

Route::get('/article', 'ArticleController@index')->name('top');

Route::resource('articles', 'ArticleController', ['only' => ['create', 'store', 'show', 'edit', 'update', 'destroy']]);

Route::resource('comments', 'CommentsController', ['only' => ['store']]);

Route::post('/articles/{articles}/likes', 'LikesController@store');

Route::post('/articles/{articles}/likes/{like}', 'LikesController@destroy');

Route::get('/mypage' , 'MypageController@index');

complexshare/app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Auth;
use App\like;

class Article extends Model
{
    protected $fillable = ['title', 'body', 'user_id'];

    public function users()
    {
        return $this->belongsto('App\User');

    }

    public function comments(){

        return $this->hasmany('App\Comment');
    }

    public function likes(){
        return $this->hasmany('App\like');
    }

    public function like_by(){
        return Like::where('user_id', Auth::user()->id)->first();
    }


}

complexshare/app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Article;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;
use App\User;

class ArticleController extends Controller
{
    public function index()
    {

        $articles = Article::orderBy('created_at', 'desc')->paginate(10);

        return view('articles.index', ['articles' => $articles]);
    }


    public function create()
    {
        return view('articles.create');
    }

    public function store(Request $request)
    {

        $article = new Article;
        $article->user_id = $request->user_id;
        $article->title = $request->title;
        $article->body = $request->body;
        $article->save();

        return redirect()->route('top');
    }
    public function __construct()
    {
      $this->middleware('auth', array('except' => 'index'));
    }


    public function show($id) {
        $article = Article::findOrFail($id); 
  
        $like = $article->likes()->where('user_id', Auth::user()->id)->first();
  
        return view('articles.show')->with(array('article' => $article, 'like' => $like));
      }



    public function edit($article_id)
    {
        $article = Article::findOrFail($article_id);

        return view('articles.edit', ['article' => $article,]);
    }

    public function update($article_id, Request $request)
    {
        $params = $request->validate([
            'title' => 'required|max:50',
            'body' => 'required|max:2000',
        ]);

        $article = Article::findOrFail($article_id);
        $article->fill($params)->save();

        return redirect()->route('articles.show', ['article' => $article]);
    }

    public function destroy($article_id)
    {

        $article = Article::findOrFail($article_id);

        DB::transaction(function () use ($article) {
            $article->comments()->delete();
            $article->delete();
        });

        return redirect()->route('top');
    }
}

complexshare/resources/views/articles/create.blade.php
@extends('layouts.app');

@section('content');
<div class="container mt-4">
    <div class="border p-4">
        <h1 class="h5 mb-4">
            投稿の新規作成
        </h1>

        <form method="POST" action="{{ route('articles.store') }}">
            @csrf
            <input type="hidden" name="user_id" value="{{Auth::id()}}">

            <fieldset class="mb-4">
                <div class="form-group">
                    <label for="title">
                        タイトル
                    </label>
                    <input id="title" name="title" class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" value="{{ old('title') }}" type="text">

                    @if($errors->has('title'))
                    <div class="invalid-feedback">
                        {{$errors->first('title')}}
                    </div>
                    @endif
                </div>
                <div class="form-group">
                    <label for="body">
                        本文
                    </label>

                    <textarea id="body" name="body" class="form-control {{ $errors->has('body') ? 'is-invalid' : '' }}" rows="4">{{ old('body') }}</textarea>
                    @if ($errors->has('body'))
                    <div class="invalid-feedback">
                        {{$errors->has('body')}}
                    </div>
                    @endif
                </div>

                <div class="mt-5">
                    <a class="submit" href="/article">
                        キャンセル
                    </a>

                    <button type="submit" class="submit">
                        投稿する
                    </button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
@endsection

complexshare/resources/views/articles/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container mt-4">
    <div class="border p-4">
        <h1 class="h5 mb-4">
            投稿編集
        </h1>

        <form method="POST" action="{{route('articles.update', ['article' => $article]) }}">
            @csrf
            @method('PUT')

            <fieldset class="mb-4">
                <div class="form-group">
                    <label for="title">
                        タイトル
                    </label>
                    <input id="title" name="title" class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" value="{{ old('title') ?: $article->title }}" type="text">
                    @if($errors->has('title'))
                    <div class="invalid-feedback">
                        {{$errors->first('title')}}
                    </div>
                    @endif
                </div>
                <div class="form-group">
                    <label for="body">
                        本文
                    </label>

                    <textarea id="body" name="body" class="form-control {{ $errors->has('body') ? 'is-invalid' : '' }}" rows="4">{{ old('body') ?: $article->body }}</textarea>
                    @if ($errors->has('body'))
                    <div class="invalid-feedback">
                        {{$errors->first('body')}}
                    </div>
                    @endif
                </div>
                <div class="mt-5">
                    <a class="btn btn-secondary" href="{{ route('articles.show', ['artcle' => $article]) }}">
                        キャンセル
                    </a>
                    <button type="submit" class="btn btn-primary">
                        更新する
                    </button>
                </div>
            </fieldset>


        </form>
    </div>
</div>
@endsection

complexshare/resources/views/articles/index.blade.php
@extends('layouts.app')


@section('content')
<div class="mb-4">
    <a href="{{ route('articles.create') }}" class="submit">
        投稿を新規作成する
    </a>
</div>

<nav class="menu">
  <ul>
    <li>Home
    <li>Blog
    <li>About
  </ul>
</nav>
<div id="cardlayout-wrap">
    <!-- カードレイアウトをラッピング -->
    @foreach ($articles as $article)
    <section class="card-list">
        <a class="card-link" href="#">
            <h2 class="card-title">{{ $article->title }}</h2>
            <p class="card-text-tax"> {!! nl2br(e(str_limit($article->body, 200))) !!}</p>
        </a>
        <a class="card-link" href="{{ route('articles.show', ['article' => $article]) }}">
            続きを読む
        </a>
        <div class="card-footer">
            <span class="mr-2">
                投稿日時 {{ $article->created_at->format('Y.m.d') }}
            </span>
    </section>

    @endforeach
</div>

<div class="d-flex justify-content-center mb-5">
    {{ $articles->links() }}
</div>





@endsection

complexshare/resources/views/articles/show.blade.php
@extends('layouts.app')

@section('content')
<div class='contaniner mt-4'>

    <div class='border p-4'>
        <h1 class="h5 mb-4">
            {{$article->title}}
        </h1>

        <p class="mb-5">
            {!! nl2br(e($article->body)) !!}
        </p>

        <section>
            <h2 class="h5 mb-4">
                コメント
            </h2>

            <form class="mb-4" method="POST" action="{{ route('comments.store') }}">
                @csrf
                <input name="article_id" type="hidden" value="{{$article->id}}">
                <input type="hidden" name="user_id" value="{{Auth::id()}}">
                <div class="form-group">
                    <label for="body">
                        本文
                    </label>
                    <textarea id="body" name="body" class="form-control {{ $errors->has('body') ? 'is-invalid' : '' }}" rows="4">{{ old('body') }}</textarea>
                    @if ($errors->has('body'))
                    <div class="invalid-feedback">
                        {{ $errors->first('body') }}
                    </div>
                    @endif
                </div>
                <div class="mt-4">
                    <button type="submit" class="btn btn-primary">
                        コメントする
                    </button>
                    <a href="/article" class="btn btn-primary">戻る</a>
                </div>
            </form>
            @if (Auth::check())
            @if ($like)
            {{ Form::model($article, array('action' => array('LikesController@destroy', $article->id, $like->id))) }}
            <button type="submit">
                いいね {{ $article->likes_count }}
            </button>
            {!! Form::close() !!}
            @else
            {{ Form::model($article, array('action' => array('LikesController@store', $article->id))) }}
            <button type="submit">
                いいね {{ $article->likes_count }}
            </button>
            {!! Form::close() !!}
            @endif
            @endif
            @forelse($article->comments as $comment)

            <div class="border-top p-4">
                <time class="text-secondary">
                    {{$comment->created_at->format('Y.m.d H:i')}}

                </time>
                <p class="mt-2">
                    {!! nl2br(e($comment->body)) !!}
                </p>

            </div>

            @empty
            <p>まだコメントはありません</p>
            @endforelse
        </section>
    </div>
</div>
@endsection


</section>